### ISSUE TITLE
Extract API related terms from changesets

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/KnowHows#12]
*Option 1:*
1. Parse SO dump for single term '<code></code>' terms
2. Select terms that occur above a certain frequency threshold (or could use a supervised approach using Conditional Random Field on the surrounding sentence. Maybe using MALLET http://mallet.cs.umass.edu/
3. Make sure to save the tags for the SO post with the term for subsequent filtering (some tag filtering could be prudent here)
3. Use the terms to lookup each individual term in the changeset. Only store terms that occur in the dictionary.

**Comment by AlexAplin** [comment]
[dictionaries.zip](https://github.com/vcu-swim-lab/KnowHows/files/1538330/dictionaries.zip)

Contains unfiltered full dictionaries for each language. Format is `<# of occurences> <term>` sorted by occurences. Posts containing at least one of these tags were considered: `["java", "android", "python", "python-3.x", "go", "javascript", "angularjs", "node.js", "reactjs", "typescript", "jquery" "c", "c++", "c#", ".net", "swift", "ios", "perl"]`. Some caveats:

1. We only consider inline code blocks that are one word including hyphens and digits.
2. No threshold filtering of terms. I have this implemented, but I decided to include all results. There's a pretty long tail with a lot of junk.
3. Counts are unweighted, so unique posts with recurring use of a single term are counted multiple times. Can be solved by instead working with a structure that saves posts with isolated terms instead of just the terms. Probably what we should do too to save the other tags associated with a post.
4. Only the first found tag is considered for the dictionary. My understanding is that tags are sorted from most to least popular, so `reactjs` reflects only those posts that aren't also tagged `javascript`.
5. Any other tags? See https://stackoverflow.com/tags.

**Comment by damevski** [comment]
We aren't going to do this, for now
