### ISSUE TITLE
finish Solr and GitHub integration

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/KnowHows#7]
Initial implementation for auth and installation of the bot/app

**Comment by damevski** [comment]
https://docs.microsoft.com/en-us/bot-framework/channel-connect-slack

**Comment by damevski** [comment]
It will be Slack App. We need to implement a website

**Comment by seefo** [comment]
https://github.com/vcu-swim-lab/HelpMeCode/commit/df27be37408676c8544e154b48bf9055801a2424 takes care of most of this

what has been done:
* registered api endpoints and processes for oauth registration of slack and github apps
* implemented github/slack services
* slack and github 3rd party apps have been created and client ids/secrets prepared on their websites
* incoming index page has been created

whats left:
* we need to host it somewhere so that we can test integration with slack/github 
* implement functionality behind slash commands
* refactor GitAuth library to integrate with how we obtain `access_token` through our api
* update our index page with information about KnowHows/this slack bot

**Comment by seefo** [comment]
Here is where are are as of https://github.com/vcu-swim-lab/KnowHows/commit/9485da0d16f72dc11f4e2221f5ecf320756c7be7.

Whats done:

- Users can now authorize a channel to index their repositories from their GitHub on a per-channel basis
- Once a user has authenticated with GitHub, their repository list is obtained 

Whats left:

- Need to change GitHub OAuth scope so that we require as little permissions as possible (https://github.com/vcu-swim-lab/KnowHows/blob/master/Website/Controllers/GitHubController.cs#L20)
- Discuss user story for deciding which repositories you want indexed in a channel, searching, etc.

**Comment by damevski** [comment]
add another web page after the GH authentication to select repos

**Comment by seefo** [comment]
Finished as of https://github.com/vcu-swim-lab/KnowHows/commit/f1aba4ab51e5a75690e4ea6205ff85d8c5c13130
